### ISSUE TITLE
Cropped Image

### ISSUE THREAD

**Issue by GiselleMartinez006** [nadyajackson/portfolio#1]
After some inspecting I discovered your image comes from here (although I think you already know that part) 

https://github.com/nadyajackson/portfolio/blob/7f48795af91f1ffa34f30252f86a12b29d18876e/pages/index.js#L49-L50

The problem with this is that it creates two spans and wraps them around your img tag. Both of these come with built-in inline style that affects the image and everything around it AND it does not change AT ALL when I try to style either of them - because inline style can't be overridden by css class or tag name selectors.  

With that said I googled for a way to get rid of the spans o (or change them) and came upon this stackoverflow answer: 
[link to answer](https://stackoverflow.com/questions/70210003/how-to-remove-the-wrapper-spans-from-next-image-in-next-js)

It asks to add `layout="raw" ` to your Image component to get rid of the spans, and to enable it (because it gives an error right after adding it) you need to make a change to the next.config.js : 

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  experimental: { images: { layoutRaw: true } } //change here
}

module.exports = nextConfig

```

Image is not centered after the change, but I believe all you wanted was to be able to see your full image 🤗 with that said, getting rid of this line and adding some flex to profile should do the trick. 

(this line is the one adding that margin to your img within your css)
https://github.com/nadyajackson/portfolio/blob/7f48795af91f1ffa34f30252f86a12b29d18876e/styles/globals.css#L78

## Let me know how it goes!

**Comment by nadyajackson** [comment]
You're a literal life saver! It worked and only needed one CSS fix to recenter it.
